# Generated by Django 4.1 on 2023-01-04 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ko', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('name_ja', models.CharField(blank=True, max_length=128, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nendoroid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True)),
                ('name_ko', models.CharField(blank=True, max_length=256)),
                ('name_en', models.CharField(blank=True, max_length=256)),
                ('name_ja', models.CharField(blank=True, max_length=256)),
                ('release_date', models.JSONField(blank=True, null=True)),
                ('image_link', models.CharField(blank=True, max_length=256)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('numbering', models.CharField(blank=True, max_length=5)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nendoroid.manufacturer')),
                ('owner', models.ManyToManyField(blank=True, related_name='nendoroid_owned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sculptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('name_ja', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('name_ko', models.CharField(blank=True, max_length=128, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ko', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('name_ja', models.CharField(blank=True, max_length=128, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NendoroidPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='nendoroid_photo')),
                ('nendoroid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nendoroid.nendoroid')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='nendoroid',
            name='sculptor',
            field=models.ManyToManyField(blank=True, related_name='nendoroid', to='nendoroid.sculptor'),
        ),
        migrations.AddField(
            model_name='nendoroid',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nendoroid.series'),
        ),
    ]
