# Generated by Django 4.1 on 2022-08-24 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ko', models.CharField(blank=True, max_length=64)),
                ('name_en', models.CharField(blank=True, max_length=64)),
                ('name_ja', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ko', models.CharField(blank=True, max_length=64)),
                ('name_en', models.CharField(blank=True, max_length=64)),
                ('name_ja', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Sculptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ko', models.CharField(blank=True, max_length=64)),
                ('name_en', models.CharField(blank=True, max_length=64)),
                ('name_ja', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ko', models.CharField(blank=True, max_length=64)),
                ('name_en', models.CharField(blank=True, max_length=64)),
                ('name_ja', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Nendoroid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True)),
                ('name_ko', models.CharField(blank=True, max_length=64)),
                ('name_en', models.CharField(blank=True, max_length=64)),
                ('name_ja', models.CharField(blank=True, max_length=64)),
                ('gsc_number', models.IntegerField(null=True)),
                ('release_date', models.JSONField(blank=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('cooperation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nendoroid.cooperation')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nendoroid.manufacturer')),
                ('sculptor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nendoroid.sculptor')),
                ('series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nendoroid.series')),
            ],
        ),
    ]
