# Generated by Django 4.1 on 2023-01-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nendoroid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nendoroidphoto',
            name='photo',
            field=models.URLField(blank=True, max_length=256),
        ),
    ]
