# Generated by Django 4.1 on 2022-08-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nendoroid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nendoroid',
            name='cooperation',
        ),
        migrations.RemoveField(
            model_name='nendoroid',
            name='image',
        ),
        migrations.RemoveField(
            model_name='nendoroid',
            name='sculptor',
        ),
        migrations.DeleteModel(
            name='Cooperation',
        ),
        migrations.AddField(
            model_name='nendoroid',
            name='sculptor',
            field=models.ManyToManyField(null=True, related_name='nendoroid', to='nendoroid.sculptor'),
        ),
    ]
