# Generated by Django 4.1 on 2023-01-06 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nendoroid', '0002_alter_nendoroidphoto_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nendoroidphoto',
            old_name='photo',
            new_name='photoURL',
        ),
    ]
